### ISSUE TITLE
Provide example(s)

### ISSUE THREAD

**Issue by alexchandel** [servo/cocoa-rs#30]
I can't tell how to use this library to create a Cocoa GUI idiomatically. This is all I could piece together from the source and test code:

```rust
extern crate cocoa;

use cocoa::base::{nil, ObjCMethodCall};
use cocoa::appkit::{NSApp, NSRect, NSPoint, NSSize};

static NSApplicationActivationPolicyRegular: int = 0i;
static NSTitledWindowMask: int = 1i;
static NSBackingStoreBuffered: int = 2i;

fn main() {
	let app_name = "Hello World!";

	unsafe {
		let app = NSApp();
		app.send("setActivationPolicy:", (NSApplicationActivationPolicyRegular));

		let window = "NSWindow".send("alloc", ()).send(
			"initWithContentRect:styleMask:backing:defer:",
			(
				NSRect {
					origin: NSPoint {x: 0., y: 0.},
					size: NSSize {width: 200., height: 200.}
				},
				NSTitledWindowMask,
				NSBackingStoreBuffered,
				false
			)
		);
		window.send("cascadeTopLeftFromPoint:", (NSPoint {x: 20., y: 20.}));
		window.send("setTitle:", (app_name));
		window.send("makeKeyAndOrderFront:", (nil));

		app.send("activateIgnoringOtherApps:", (true));
		app.send("run", ());
	}
}
```

**Comment by SirVer** [comment]
Could we maybe get a more complete example? Maybe a text view or something? Maybe some custom widget subclassing one of the core ones?

Background:
I am playing around with this crate - not having done any significant objective-c before I have a hard time grasping its concepts. I want to duplicate a text rendering interface similar to the one that MacVim uses. I see [https://github.com/macvim-dev/macvim/blob/master/src/MacVim/MMCoreTextView.h#L19](there) that it's view widget inherits from `NSView<NSTextView>`. I cannot fathom how inheritance should be expressed in `cocoa-rs` and would much appreciate an example or pointer.

**Comment by SSheldon** [comment]
@SirVer, if you want to create complicated custom Objective-C classes I'd definitely recommend just writing them in Objective-C and compiling it with a build.rs script. However, if you're curious how a small custom class can be constructed directly in Rust, there's functionality available through the objc crate and here's an example: https://github.com/SSheldon/rust-objc-foundation/blob/47048ed/examples/custom_class.rs

**Comment by SirVer** [comment]
@SSheldon Thanks, that was what I was looking for. :+1:
